version: "3"
services:
  server:
    container_name: server
    build:
      dockerfile: Dockerfile
    ports:
      - 3333:8080
      - 2525:8080
      - 8080:8080
    environment:
      - PORT=8080
